import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { PrototypeModal } from '@prototype/ui';
import { FaIcon } from '@prototype/ui/Icon';
export function RuleConfigListBatchModals({ showBatchConfirm, showBatchDelete, batchScope, confirmableCount, onCloseConfirm, onCloseDelete, onBatchConfirm, onBatchDelete, }) {
    return (_jsxs(_Fragment, { children: [showBatchConfirm && (_jsx(PrototypeModal, { title: "\u786E\u8BA4\u6279\u91CF\u786E\u8BA4", onClose: onCloseConfirm, size: "md", children: _jsxs("div", { className: "text-center py-4", children: [_jsx(FaIcon, { className: "fas fa-check-circle text-5xl text-green-500 mb-4" }), _jsx("p", { className: "text-base text-text-secondary mb-2", children: batchScope.isFull
                                ? `未勾选记录，确定要全量确认当前列表 ${batchScope.count} 条记录吗？`
                                : `确定要批量确认选中的 ${batchScope.count} 条记录吗？` }), _jsxs("p", { className: "text-sm text-text-muted mb-6", children: ["\u5176\u4E2D ", confirmableCount, " \u6761\u7B26\u5408\u786E\u8BA4\u6761\u4EF6\uFF0C\u4E0D\u7B26\u5408\u7684\u5C06\u81EA\u52A8\u8DF3\u8FC7\u3002"] }), _jsxs("div", { className: "flex justify-center gap-3", children: [_jsx("button", { type: "button", className: "px-6 py-2 bg-gray-200 rounded-lg", onClick: onCloseConfirm, children: "\u53D6\u6D88" }), _jsx("button", { type: "button", className: "px-6 py-2 bg-green-600 text-white rounded-lg", onClick: onBatchConfirm, children: "\u786E\u8BA4" })] })] }) })), showBatchDelete && (_jsx(PrototypeModal, { title: "\u786E\u8BA4\u6279\u91CF\u5220\u9664", onClose: onCloseDelete, size: "md", children: _jsxs("div", { className: "text-center py-4", children: [_jsx(FaIcon, { className: "fas fa-exclamation-triangle text-5xl text-red-500 mb-4" }), _jsxs("p", { className: "text-base text-text-secondary mb-6", children: [batchScope.isFull
                                    ? `未勾选记录，确定要全量删除当前列表 ${batchScope.count} 条记录吗？`
                                    : `确定要删除选中的 ${batchScope.count} 条记录吗？`, _jsx("br", {}), "\u6B64\u64CD\u4F5C\u4E0D\u53EF\u64A4\u9500\u3002"] }), _jsxs("div", { className: "flex justify-center gap-3", children: [_jsx("button", { type: "button", className: "px-6 py-2 bg-gray-200 rounded-lg", onClick: onCloseDelete, children: "\u53D6\u6D88" }), _jsx("button", { type: "button", className: "px-6 py-2 bg-red-500 text-white rounded-lg", onClick: onBatchDelete, children: "\u786E\u8BA4\u5220\u9664" })] })] }) }))] }));
}
